apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app-deployment
spec:
  replicas: 3 # Chạy 3 bản sao của ứng dụng
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs-app-container
        image: navata/my-app-14:v4 # Sử dụng image đã xây dựng
        ports:
        - containerPort: 3000
        resources: # Giới hạn tài nguyên để tránh chiếm dụng quá mức
          limits:
            memory: "128Mi"
            cpu: "500m"