export const revalidate = 30;
export const dynamic = "force-static";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getTime = async () => new Date().getTime();

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const time = await getTime();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="w-full p-4 bg-gray-100">
            <Link href="/">Home + {time}</Link>
          </div>
          <div className="p-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
